### ISSUE TITLE
Assumed PDFDocument default import

### ISSUE THREAD

**Issue by j-wenning** [natancabral/pdfkit-table#46]
The PDFDocument constructor import does not explicitly retrieve the `default` export from the required `pdfkit` module, causing builds using newer versions of Babel to fail at runtime.

```
TypeError: Class extends value #<Object> is not a constructor or null
    at eval (index.js:9:37)
    at ./node_modules/pdfkit-table/index.js (home.js:1359:1)
    at __webpack_require__ (app.js:294:33)
    at fn (app.js:550:21)
    at eval (pdf.ts:7:70)
    at ./src/lib/pdf.ts (home.js:51:1)
    at __webpack_require__ (app.js:294:33)
    at fn (app.js:550:21)
    at eval (index.js??clonedRuleSet-41.use[1]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/pages/nav/HomePage.vue?vue&type=script&lang=ts&setup=true:3:66)
    at ./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js??clonedRuleSet-41.use[1]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/pages/nav/HomePage.vue?vue&type=script&lang=ts&setup=tru
```

**Comment by gauravbordoloi** [comment]
@j-wenning @natancabral Any resolution for this?

**Comment by j-wenning** [comment]
I elected to manually rewrite the source import with a Webpack rule using string-replace-loader, rather than doing some excessive amount of fiddling. 
```
{
  test: /pdfkit-table\/index\.js$/,
  loader: 'string-replace-loader',
  options: {
    search: 'require("pdfkit")',
    replace: 'require("pdfkit").default',
  },
},
```
